#workflow -> Pipelines -> CI
name: CI Pipeline

#Event Triggers -> When to run the workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #server
    runs-on: ubuntu-latest
    #version of node to use to test on app
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    #switch branch
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        #Actual commands to run
    - name : Build Command
    - run:  echo "Building APP"

    - name : Test Command
    - run:  echo "Testing APP"
